[package]
name            =  "bars"
version         =  "0.0.1"
description     =  "Bare Metal Rust workout"
authors         = ["Dmitry Ponyatov <dponyatov@gmail.com>"]
license         =  "MIT"
repository      =  "https://github.com/ponyatov/bars"
edition         =  "2024"

[[bin]]
name = "bars"
path = "src/bars.rs"

[dependencies]

[target.'cfg(all(target_arch = "x86"))'.dependencies]
x86             = "0.52"
raw-cpuid       = "11.6"

[target.'cfg(target_os = "none")'.dependencies]

[target.'cfg(target_os = "linux")'.dependencies]
const_format    = "0.2"
libc            = "0.2"
memmap2         = "0.9"
