[build]
target    = ".cargo/i386-pc-none.json"
jobs      = 4

[target.x86_64-unknown-linux-gnu]
rustflags = ["--cfg", "feature=\"pc,i5,linux\""]
linker    = "x86_64-linux-gnu-gcc"

[target.i386-pc-none]
rustflags = ["--cfg", "feature=\"pc,i486,none\""]
linker    = "rust-lld"
runner    = "qemu-system-i386 -kernel"

[unstable]
build-std = ["core", "compiler_builtins"]

[source.crates-io]
replace-with = 'ustc'

[source.ustc]
registry = "sparse+https://mirrors.ustc.edu.cn/crates.io-index/"
[source.tuna]
registry = "sparse+https://mirrors.tuna.tsinghua.edu.cn/crates.io-index/"
